### ISSUE TITLE
crashes after the loading screen

### ISSUE THREAD

**Issue by Q-CHAYKA-Q** [SWeeb87/AOT-Revive-Public-BETA-Releases#1]
Poco F3 8/256
Snapdragon 870
HyperOS 1.0.3.0.TKHRUXM
Android 13 TKQ1.221114.001
Game Version 1.2.0 Beta4

**Comment by Q-CHAYKA-Q** [comment]
Poco F3 8/256
HyperOS 1.0.3.0.TKHRUXM
Android 13 TKQ1.221114.001 

Uploading Screenrecorder-2024-09-13-14-27-30-628.mp4…

**Comment by Q-CHAYKA-Q** [comment]
Here's a recording of how it happens 
https://youtube.com/shorts/7DaFKQQY0o0?si=_ujrXqLnGSl2jmRu

**Comment by SWeeb87** [comment]
> Here's a recording of how it happens https://youtube.com/shorts/7DaFKQQY0o0?si=_ujrXqLnGSl2jmRu

This is a VR game for quest 2 and 3, not a mobile game
